title: "Herman Parent Faculty Club"
email: "hello@hermanpfc.org"
description: "Connecting parents, supporting students."
baseurl: "" # leave blank unless site is served from a subpath
url: "https://hermanparentfacultyclub.github.io/"     # your production URL, e.g. https://your-org.github.io
markdown: kramdown
permalink: pretty
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

