title: "Herman Parent Faculty Club"
email: "contact@hermanparentfacultyclub.org"
description: "Connecting parents, supporting students."
baseurl: "" # leave blank unless site is served from a subpath
url: ""     # your production URL, e.g. https://your-org.github.io
markdown: kramdown
permalink: pretty
