title: "Herman Parent Faculty Club"
email: "hello@hermanpfc.org"
description: "Connecting parents, supporting students."
baseurl: "" # leave blank unless site is served from a subpath
url: "https://hermanpfc.org/"     # your production URL, e.g. https://your-org.github.io
markdown: kramdown
permalink: pretty
